#include <Arduino.h>
#include <Wire.h>
enum class ControlMode:uint8_t{Safe,RcManual,RosAutonomous};extern ControlMode controlMode;extern bool armed;extern bool estopOkay();extern TwoWire OledWire;extern uint32_t lastSequence;
void initializeUltrasonicController();void updateUltrasonicController();void initializeEsp32SettingsController();void updateEsp32SettingsController();
uint16_t espSettingRcMinUs(uint8_t);uint16_t espSettingRcCenterUs(uint8_t);uint16_t espSettingRcMaxUs(uint8_t);uint16_t espSettingRcDeadbandUs();uint16_t espSettingRcTimeoutMs();uint16_t espSettingAuxIdleMv();uint16_t espSettingAuxMaxMv();uint16_t espSettingAuxReverseGuardMs();uint16_t espSettingAuxRampStep();bool espSettingAuxReverseActiveHigh();uint16_t espSettingRosAuxTimeoutMs();
namespace Pins{constexpr uint8_t RC=36,REV=12;}namespace C{constexpr uint8_t ADDR=0x61;constexpr uint16_t SAFE=0,ISR_MIN=750,ISR_MAX=2250;constexpr uint32_t UPDATE=20,TEL=200,MAGIC=0xA5000000UL,MASK=0xFFF00000UL,VMASK=0x7FFUL;}
struct Rc{volatile uint32_t rise=0,last=0;volatile uint16_t pulse=0;};static portMUX_TYPE mux=portMUX_INITIALIZER_UNLOCKED;static Rc rc;static bool init=false,mcp=false,rcValid=false;static uint16_t rcUs=0,throttle=0;static int16_t ros=0,target=0,actual=0;static uint32_t rosMs=0,lastSeq=0,revReady=0,lastUpd=0,lastTel=0;static int8_t applied=1,pending=0;
static uint8_t sum(const char*t){uint8_t v=0;while(*t)v^=*t++;return v;}static void frame(const String&b){Serial.print(b);Serial.print('*');uint8_t v=sum(b.c_str());if(v<16)Serial.print('0');Serial.println(v,HEX);}static void IRAM_ATTR onRc(){uint32_t n=micros();portENTER_CRITICAL_ISR(&mux);if(digitalRead(Pins::RC))rc.rise=n;else{uint32_t w=n-rc.rise;if(w>=C::ISR_MIN&&w<=C::ISR_MAX){rc.pulse=w;rc.last=n;}}portEXIT_CRITICAL_ISR(&mux);}
static bool present(){OledWire.beginTransmission(C::ADDR);return OledWire.endTransmission()==0;}static bool writeThrottle(uint16_t mv){if(!mcp)return false;uint16_t v=(uint32_t)min<uint16_t>(mv,5000)*4095/5000;OledWire.beginTransmission(C::ADDR);OledWire.write((v>>8)&0x0F);OledWire.write(v&0xFF);if(OledWire.endTransmission()!=0){mcp=false;throttle=0;return false;}throttle=mv;return true;}static void setRev(bool r){bool l=espSettingAuxReverseActiveHigh()?r:!r;digitalWrite(Pins::REV,l?HIGH:LOW);applied=r?-1:1;}
static bool readRc(uint16_t&p){uint16_t pulse;uint32_t last,now=micros();portENTER_CRITICAL(&mux);pulse=rc.pulse;last=rc.last;portEXIT_CRITICAL(&mux);bool ok=pulse>=espSettingRcMinUs(6)&&pulse<=espSettingRcMaxUs(6)&&last&&now-last<=uint32_t(espSettingRcTimeoutMs())*1000UL;p=ok?pulse:0;return ok;}static int16_t pulseCmd(uint16_t p){int32_t c=espSettingRcCenterUs(6),db=espSettingRcDeadbandUs(),d=int32_t(p)-c;if(abs(d)<=db)return 0;if(d>0){uint32_t span=max<int32_t>(1,espSettingRcMaxUs(6)-c-db);return constrain((d-db)*1000/int32_t(span),0,1000);}uint32_t span=max<int32_t>(1,c-espSettingRcMinUs(6)-db);return constrain((d+db)*1000/int32_t(span),-1000,0);}static uint16_t cmdMv(int16_t c){uint16_t m=constrain(abs(c),0,1000);if(!m)return 0;uint32_t lo=espSettingAuxIdleMv(),hi=espSettingAuxMaxMv();return lo+(uint32_t)m*(hi-lo)/1000;}static int8_t sgn(int16_t v){return v>0?1:v<0?-1:0;}static int16_t toward(int16_t a,int16_t t){int16_t st=espSettingAuxRampStep();return a<t?min<int16_t>(a+st,t):a>t?max<int16_t>(a-st,t):a;}
static void capture(){uint32_t s=lastSequence;if(s==lastSeq||(s&C::MASK)!=C::MAGIC)return;lastSeq=s;ros=constrain(int32_t(s&C::VMASK)-1000,-1000L,1000L);rosMs=millis();}void stopAuxMotorController(){target=actual=0;pending=0;revReady=0;if(mcp)writeThrottle(0);else throttle=0;}
void initializeAuxMotorController(){if(init)return;pinMode(Pins::RC,INPUT);pinMode(Pins::REV,OUTPUT);setRev(false);attachInterrupt(digitalPinToInterrupt(Pins::RC),onRc,CHANGE);mcp=present();if(mcp){writeThrottle(0);Serial.println("EVT,AUXMOTOR,MCP4725_OK,0x61,RUNTIME_CONFIG");}else Serial.println("ERR,AUXMOTOR_MCP4725_NOT_FOUND,0x61");init=true;}void setAuxMotorRosCommand(int16_t c){ros=constrain(c,-1000,1000);rosMs=millis();}
void updateAuxMotorController(){if(!init)initializeAuxMotorController();capture();uint32_t now=millis();if(now-lastUpd<C::UPDATE)return;lastUpd=now;rcValid=readRc(rcUs);if(!estopOkay()||!armed||!mcp||controlMode==ControlMode::Safe)stopAuxMotorController();else{bool valid=false;int16_t req=0;if(controlMode==ControlMode::RcManual){valid=rcValid;if(valid)req=pulseCmd(rcUs);}else{valid=rosMs&&now-rosMs<=espSettingRosAuxTimeoutMs();if(valid)req=ros;}if(!valid||!req)stopAuxMotorController();else{target=req;int8_t rs=sgn(req);if(rs!=applied){actual=0;writeThrottle(0);if(pending!=rs){pending=rs;revReady=now+espSettingAuxReverseGuardMs();}else if((int32_t)(now-revReady)>=0){setRev(rs<0);pending=0;revReady=now+espSettingAuxReverseGuardMs();}}else if(revReady&&(int32_t)(now-revReady)<0)writeThrottle(0);else{revReady=0;pending=0;actual=toward(actual,req);if(!writeThrottle(cmdMv(actual)))actual=0;}}}if(now-lastTel>=C::TEL){lastTel=now;frame(String("AUXTEL,")+now+","+rcUs+","+(rcValid?1:0)+","+ros+","+target+","+actual+","+applied+","+throttle+","+(mcp?1:0));}}
uint16_t getAuxMotorRcPulseUs(){return rcUs;}bool getAuxMotorRcValid(){return rcValid;}int16_t getAuxMotorRosCommand(){return ros;}int16_t getAuxMotorTarget(){return target;}int16_t getAuxMotorActual(){return actual;}int8_t getAuxMotorDirection(){return applied;}uint16_t getAuxMotorThrottleMv(){return throttle;}bool getAuxMotorMcpReady(){return mcp;}
void serialEventRun(void){initializeEsp32SettingsController();updateEsp32SettingsController();updateAuxMotorController();updateUltrasonicController();}
